### ISSUE TITLE
about training model

### ISSUE THREAD

**Issue by gxxdd** [Zplusdragon/PLIP#13]
Thank you very much for your work！
Now I hope to train my own model to better understand the methods involved. What should I do

**Comment by Zplusdragon** [comment]
We will release the training code after this paper is accepted. Please maintain continuous attention.

**Comment by gxxdd** [comment]
Thank you for your attention. I don’t understand the code structure. What is the function of the Downstreams/CPCM-C/train.py file?

**Comment by gxxdd** [comment]
I'm trying to run train.py now, but I'm currently having some problems：
[init] == local rank: 1, global rank: 0 ==
/home/admin/anaconda3/envs/gxd_torchreid/lib/python3.7/site-packages/torchvision/transforms/transforms.py:330: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
Some weights of the model checkpoint at /home/admin/gxd/project/PLIP-main/bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
The optimizer is adan
lr_scheduler is StepLR
The image model is: ModifiedResNet
The language model is: bert-base-uncased
Number of model parameters: 147239776
Checkpoints are saved in: CUHK-CMPMC
The original learning rate is 0.0001
            =======  Training  ======= 

**********************************************************
>>> Training epoch 1
learning rate warm_up
Traceback (most recent call last):
  File "Downstreams/CMPM-C/train.py", line 192, in <module>
    main()
  File "Downstreams/CMPM-C/train.py", line 189, in main
    train(args)
  File "Downstreams/CMPM-C/train.py", line 157, in train
    train_dataloader):
  File "/home/admin/anaconda3/envs/gxd_torchreid/lib/python3.7/site-packages/prefetch_generator/__init__.py", line 116, in next
    raise next_item
  File "/home/admin/anaconda3/envs/gxd_torchreid/lib/python3.7/site-packages/prefetch_generator/__init__.py", line 98, in run
    for item in self.generator: self.queue.put((True , item))
  File "/home/admin/anaconda3/envs/gxd_torchreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/admin/anaconda3/envs/gxd_torchreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/admin/anaconda3/envs/gxd_torchreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/admin/anaconda3/envs/gxd_torchreid/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/admin/anaconda3/envs/gxd_torchreid/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/admin/anaconda3/envs/gxd_torchreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/admin/anaconda3/envs/gxd_torchreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/admin/gxd/project/PLIP-main/Downstreams/CMPM-C/dataloader.py", line 38, in __getitem__
    image = Image.open(os.path.join(self.impath, file_path)).convert('RGB')
  File "/home/admin/anaconda3/envs/gxd_torchreid/lib/python3.7/site-packages/PIL/Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/CUHK-PEDES/train_query/p2219_s2574.jpg'

**Comment by Zplusdragon** [comment]
Firstly, we pretrain the PLIP model on SYNTH-PEDES to get the pretrained model (the pretraining code is not public yet). Then, the pre-trained PLIP model can be utilized to fine-tune on downstream tasks (such as the fine-tune training code CMPM-C you mentioned).  And it seems that you have not organized the training datasets correctly.  That is why you get the problems.

**Comment by gxxdd** [comment]
Thank you for your answer. I will continue to try to solve this problem according to your answer. Thank you very much for your contribution to this field. I wish you all the best.
